/*
 * Copyright 2025 Snowflake Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 *  keywords.c
 *
 *  Knowledge about DuckDB parser keywords, and identifier quoting that
 *  accounts for DuckDB's keyword set.
 *
 *  The keyword table is generated from the vendored DuckDB kwlist.hpp by
 *  tools/generate_duckdb_kwlist.py.  Re-run that script whenever DuckDB is
 *  updated to a new release.
 */

#include "postgres.h"
#include "miscadmin.h"
#include "utils/builtins.h"

#include <string.h>

#include "pg_lake/pgduck/keywords.h"

/* Keyword categories — must match the values used in duckdb_kwlist.h */
#define UNRESERVED_KEYWORD		0
#define COL_NAME_KEYWORD		1
#define TYPE_FUNC_NAME_KEYWORD	2
#define RESERVED_KEYWORD		3

/* Simple table entry */
typedef struct DuckDBKeyword
{
	const char *keywordName;
	int			keywordCategory;
}			DuckDBKeyword;

/*
 * Keyword table, sorted alphabetically (required for bsearch).
 * Generated by tools/generate_duckdb_kwlist.py from the vendored
 * duckdb_pglake/duckdb/third_party/libpg_query/include/parser/kwlist.hpp.
 */
static const DuckDBKeyword duckDBKeywordList[] =
{
#include "duckdb_kwlist.h"
};

#define NUM_KEYWORDS (sizeof(duckDBKeywordList) / sizeof(DuckDBKeyword))

/* Comparator for bsearch */
static int
compareKeywords(const void *userKey, const void *keywordCandidate)
{
	return strcasecmp((const char *) userKey,
					  ((const DuckDBKeyword *) keywordCandidate)->keywordName);
}

/*
 * IsDuckDBReservedWord — returns true for any keyword that is not
 * UNRESERVED (i.e., RESERVED, COL_NAME, or TYPE_FUNC_NAME).
 *
 * Used by QuoteDuckDBFieldName() in parse_struct.c for struct field access.
 */
bool
IsDuckDBReservedWord(char *candidateWord)
{
	const DuckDBKeyword *found = bsearch(candidateWord,
										 duckDBKeywordList,
										 NUM_KEYWORDS,
										 sizeof(DuckDBKeyword),
										 compareKeywords);

	if (!found)
		return false;

	return found->keywordCategory != UNRESERVED_KEYWORD;
}

/*
 * ForceQuoteIdentifier — unconditionally wraps ident in double-quotes,
 * doubling any embedded double-quotes per the SQL standard.
 */
static const char *
ForceQuoteIdentifier(const char *ident)
{
	/* Worst case: every character doubled, plus two quotes and a NUL */
	char	   *result = palloc(2 * strlen(ident) + 3);
	char	   *p = result;
	const char *s;

	*p++ = '"';
	for (s = ident; *s; s++)
	{
		if (*s == '"')
			*p++ = '"';			/* double any embedded quote */
		*p++ = *s;
	}
	*p++ = '"';
	*p = '\0';
	return result;
}

/*
 * duckdb_quote_identifier — like quote_identifier() but also quotes
 * identifiers that are RESERVED_KEYWORD in DuckDB but not in PostgreSQL
 * (e.g. LAMBDA, PIVOT, QUALIFY, SUMMARIZE, DESCRIBE, SHOW, UNPIVOT).
 *
 * Use this function for any identifier that will appear in SQL sent to
 * pgduck_server.  PostgreSQL-only SQL (e.g. extension management commands,
 * SPI queries against local catalogs) should continue to use
 * quote_identifier().
 */
const char *
duckdb_quote_identifier(const char *ident)
{
	const char *pgQuoted = quote_identifier(ident);

	/*
	 * quote_identifier returns the original pointer unchanged when no quoting
	 * is needed under PostgreSQL rules.  If it returned a different pointer,
	 * the identifier is already quoted correctly — use that result.
	 */
	if (pgQuoted != ident)
		return pgQuoted;

	/*
	 * PostgreSQL doesn't think quoting is needed, but DuckDB may have
	 * stricter reserved words.  Check for a strict RESERVED_KEYWORD match.
	 */
	{
		const DuckDBKeyword *found = bsearch(ident,
											 duckDBKeywordList,
											 NUM_KEYWORDS,
											 sizeof(DuckDBKeyword),
											 compareKeywords);

		if (found && found->keywordCategory == RESERVED_KEYWORD)
			return ForceQuoteIdentifier(ident);
	}

	return ident;
}

/*
 * IsIdentChar — true for characters valid inside an unquoted SQL identifier.
 */
static inline bool
IsIdentChar(unsigned char c)
{
	return isalnum(c) || c == '_';
}

/*
 * RequoteDuckDBReservedInSQL — scan a SQL string produced by
 * pg_get_querydef() and double-quote any unquoted identifier token that
 * DuckDB's parser requires to be quoted (RESERVED_KEYWORD in DuckDB) but
 * PostgreSQL leaves unquoted.
 *
 * The scanner tracks three lexical states:
 *   • normal        — outside any quotes
 *   • single-quote  — inside '…', with '' escape
 *   • double-quote  — inside "…", with "" escape
 *
 * Only tokens in the normal state that PostgreSQL would not quote
 * (quote_identifier returns the same pointer) yet DuckDB marks as
 * RESERVED_KEYWORD are requoted.  Standard SQL literals produced by
 * pg_get_querydef — such as true, false, null — are unaffected because
 * PostgreSQL's quote_identifier() changes them (they are PG-reserved),
 * triggering the short-circuit that copies them verbatim.
 */
char *
RequoteDuckDBReservedInSQL(const char *sql)
{
	StringInfoData	out;
	const char	   *p = sql;

	initStringInfo(&out);

	while (*p)
	{
		if (*p == '\'')
		{
			/* Single-quoted literal: copy until closing quote ('' escape). */
			appendStringInfoChar(&out, *p++);
			while (*p)
			{
				char		c = *p++;

				appendStringInfoChar(&out, c);
				if (c == '\'')
				{
					if (*p == '\'')		/* escaped single-quote */
						appendStringInfoChar(&out, *p++);
					else
						break;
				}
			}
		}
		else if (*p == '"')
		{
			/* Double-quoted identifier: copy verbatim (handles "" escape). */
			appendStringInfoChar(&out, *p++);
			while (*p)
			{
				char		c = *p++;

				appendStringInfoChar(&out, c);
				if (c == '"')
				{
					if (*p == '"')		/* escaped double-quote */
						appendStringInfoChar(&out, *p++);
					else
						break;
				}
			}
		}
		else if (isalpha((unsigned char) *p) || *p == '_')
		{
			/* Collect an unquoted identifier / keyword token. */
			const char *start = p;
			int			toklen;
			char	   *tok;

			while (IsIdentChar((unsigned char) *p))
				p++;

			toklen = (int) (p - start);
			tok = palloc(toklen + 1);
			memcpy(tok, start, toklen);
			tok[toklen] = '\0';

			/*
			 * Requote only when:
			 *   1. PostgreSQL would leave it unquoted — quote_identifier
			 *      returns the same pointer, meaning no PG quoting needed.
			 *      This excludes PG-reserved literals (true, false, null)
			 *      and SQL keywords that pg_get_querydef emits in uppercase.
			 *   2. DuckDB requires it to be quoted — duckdb_quote_identifier
			 *      returns a different string (RESERVED_KEYWORD match).
			 */
			{
				const char *pgq = quote_identifier(tok);

				if (pgq == tok)
				{
					const char *duckq = duckdb_quote_identifier(tok);

					if (duckq != tok)
						appendStringInfoString(&out, duckq);
					else
						appendStringInfoString(&out, tok);
				}
				else
				{
					/* PG-reserved: a SQL keyword or literal — copy as-is. */
					appendStringInfoString(&out, tok);
				}
			}

			pfree(tok);
		}
		else
		{
			appendStringInfoChar(&out, *p++);
		}
	}

	return out.data;
}
